description: 'attraction-repulsion with 3 types particles'
dataset: '/groups/saalfeld/home/allierc/signaling/Agents/data/mechanistic, noise, chemo/chemo_full_1'

simulation:
  params: [[-1]]
  min_radius: 0
  max_radius: 5
  n_neighbors: 10
  n_particles: 300000
  n_frames: 149
  delta_t: 1
  boundary: 'periodic'
  state_type: 'sequence'

graph_model:
  particle_model_name: 'PDE_Agents_A'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1
  sparsity: 'replace_embedding_function'
  cluster_method: 'distance_plot'
  data_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'





