description: 'Boids 16 different types, division'
dataset: 'boids_division_model_1'

simulation:
  params: [[-1]]
  cell_cycle_length: [-1]
  cell_death_rate: [1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4]
  min_radius: 0.001
  max_radius: 0.04
  radius_pid: true
  max_edges: 500000
  n_particles: 512
  has_cell_division: True
  n_particles_max: 20000
  n_particle_types: 16
  n_interactions: 16
  n_frames: 8000
  sigma: 0.005
  delta_t: 0.5
  dpos_init: 5.0E-4
  boundary: 'periodic'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_B'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 256
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 20
  ylim: [-1.0E-4,1.0E-4]

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  sub_batches: 4
  n_runs: 2
  noise_level: 0
  sparsity: 'replace_embedding'
  cluster_method: 'distance_plot'
  data_augmentation: True
  data_augmentation_loop: 50
  fix_cluster_embedding: True
  device: 'auto'

