description: 'Boids 16 different types, division'
dataset: 'boids_division_model_j'

simulation:
  params: [[42.031494,  19.948257,  89.53507  ],
 [35.10319,   44.282894,  17.424503 ],
 [94.129265, 20.24777,    4.7820106]]
  cell_cycle_length:  [1.0E6, 250,200]
  cell_death_rate: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  final_cell_mass: [100, 400, 2000]
  cell_area: [1,1,1]
  min_radius: 0.001
  max_radius: 0.04
  max_edges: 500000
  n_particles: 2048
  n_particles_max: 1
  has_cell_division: True
  has_cell_death: False
  cell_inert_model_coeff: 1.0
  coeff_area: 0
  coeff_perimeter: 1.0E-2
  cell_active_model_coeff: 1.0E-2
  cell_type_map: 'cell_map_2.tif'
  n_particle_types: 3
  n_interactions: 3
  n_frames: 100
  sigma: 0.005
  delta_t: 0.5
  dpos_init: 5.0E-4
  boundary: 'periodic'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_Cell_B'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 256
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  sub_batches: 4
  n_runs: 2
  noise_level: 0
  sparsity: 'replace_embedding'
  cluster_method: 'distance_embedding'
  data_augmentation: True
  data_augmentation_loop: 50
  fix_cluster_embedding: True
  device: 'auto'

