description: 'Boids 16 different types, division'
dataset: 'boids_division_model_passive_v'

simulation:
  params: [[42.031494,  19.948257,  89.53507  ],
 [35.10319,   44.282894,  17.424503 ],
 [94.129265, 20.24777,    4.7820106],
 [ 5.2216754, 87.56955,   79.421486 ],
 [31.489408,   2.5899503, 51.467194 ],
 [89.52404,   86.077866,  50.448505 ],
 [92.9688,   91.75417,   71.636795 ],
 [58.27974,   22.423145,  19.553406 ]]
  cell_cycle_length:  [560, 1012, 976, 952, 700, 600, 772, 884]
  cell_death_rate: [0,0,0,0,0,0,0,0]
  final_cell_mass: [100, 300, 400, 500, 100, 300, 400, 500]
  cell_area: [1,1.5,2,2.5,3,3.5,4,4.5]
  min_radius: 0.001
  max_radius: 0.04
  max_edges: 500000
  n_particles: 1024
  has_cell_division: True
  has_cell_death: True
  cell_inert_model_coeff: 0.2
  coeff_area: 1
  coeff_perimeter: 2.5E-3
  cell_active_model_coeff: 0
  n_particles_max: 5000
  n_particle_types: 8
  n_frames: 1000
  sigma: 0.005
  delta_t: 0.5
  dpos_init: 5.0E-4
  boundary: 'periodic'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_Cell_B'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 256
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  sub_batches: 4
  n_runs: 2
  noise_level: 0
  sparsity: 'replace_embedding'
  cluster_method: 'distance_embedding'
  data_augmentation: True
  data_augmentation_loop: 50
  fix_cluster_embedding: True
  device: 'auto'

